name: Ruby

on:
  push:
    branches:
      - master
      - "*-stable"
  pull_request:
    branches:
      - master
      - "*-stable"

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
        with:
          ruby-version: 2.6
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake spec
      - name: RuboCop Linter Action
        uses: andrewmcodes/rubocop-linter-action@v3.3.0
        with:
          action_config_path: .github/config/rubocop_linter_action.yml
          exit_on_failure: true
      - name: Erb action
        uses: revans/erb-action@v0.0.4
